export const solarPanels = [
  {
    id: "solar-panel-1",
    category: "Solar Panel",
    series: "CE-200W/320W/350W",
    type: "Mono Half-Cut Solar Panel N-Type",
    description:
      "Positive power tolerance of 0~+3%. TOPCon Technology with Multi Busbar Technology for better light trapping and current collection. PID Resistance with excellent Anti-PID performance. Enhanced mechanical load certified to withstand wind load (2400 Pascal) and snow load (5400 Pascal).",
    warranty: {
      product: "12-year Product Warranty",
      power: "25-year Linear Power Output Warranty",
      degradation: "0.45% Annual Degradation Over 25 Years",
    },
    certifications: ["ISO9001:2025", "ISO14001:2025", "ISO45001:2025"],
    models: [
      {
        model: "CE-200W",
        maxPower: "200W (0~+5W)",
        maxPowerVoltage: "22.8V",
        maxPowerCurrent: "8.88A",
        openCircuitVoltage: "27.1V",
        shortCircuitCurrent: "9.02A",
        moduleEfficiency: "≥23%",
        operatingTemp: "-10°C~+85°C",
        maxSystemVoltage: "1000V",
        maxSeriesFuseRating: "15A",
        powerTolerance: "0~+3%",
        tempCoefficient: "-0.35%/°C",
        dimensions: "1430x680x25mm",
        weight: "9.2kg",
      },
      {
        model: "CE-320W",
        maxPower: "320W (0~+5W)",
        maxPowerVoltage: "25.5V",
        maxPowerCurrent: "13.1A",
        openCircuitVoltage: "30V",
        shortCircuitCurrent: "13.9A",
        moduleEfficiency: "≥23%",
        operatingTemp: "-40°C~+85°C",
        maxSystemVoltage: "1500V",
        maxSeriesFuseRating: "30A",
        powerTolerance: "0~+3%",
        tempCoefficient: "-0.35%/°C",
        dimensions: "1640x992x30mm",
        weight: "16.2kg",
      },
      {
        model: "CE-350W",
        maxPower: "350W (0~+5W)",
        maxPowerVoltage: "25.5V",
        maxPowerCurrent: "13.73A",
        openCircuitVoltage: "30V",
        shortCircuitCurrent: "14.55A",
        moduleEfficiency: "≥23%",
        operatingTemp: "-40°C~+85°C",
        maxSystemVoltage: "1500V",
        maxSeriesFuseRating: "30A",
        powerTolerance: "0~+3%",
        tempCoefficient: "-0.35%/°C",
        dimensions: "1640x992x30mm",
        weight: "16.2kg",
      },
    ],
    mechanicalSpecs: {
      cellType: "MONO TOPCon 182x182mm",
      numOfCells: "80 (8x10)",
      frontGlass:
        "3.2mm, Anti-Reflection Coating, High Transmission, Low Iron, Tempered Glass",
      frame: "Anodized Aluminium Alloy",
      junctionBox: "IP68 Rated",
      outputCables: "PV1 x 4.0mm, (+): 500mm, (-): 500mm or Customized Length",
    },
  },
  {
    id: "solar-panel-2",
    category: "Solar Panel",
    series: "CE-400W/420W",
    type: "Mono Half-Cut Solar Panel N-Type",
    description:
      "Positive power tolerance of 0~+3%. TOPCon Technology with Multi Busbar Technology. PID Resistance and durability against extreme environmental conditions. Reduced hot spot loss with enhanced mechanical load.",
    warranty: {
      product: "12-year Product Warranty",
      power: "25-year Linear Power Output Warranty",
      degradation: "0.45% Annual Degradation Over 25 Years",
    },
    certifications: ["ISO9001:2025", "ISO14001:2025", "ISO45001:2025"],
    models: [
      {
        model: "CE-400W",
        maxPower: "400W (0~+5W)",
        maxPowerVoltage: "31.4V",
        maxPowerCurrent: "12.7A",
        openCircuitVoltage: "34.8V",
        shortCircuitCurrent: "13.5A",
        moduleEfficiency: "≥23%",
        operatingTemp: "-40°C~+85°C",
        maxSystemVoltage: "1000/1500VDC(IEC)",
        maxSeriesFuseRating: "30A",
        powerTolerance: "0~+3%",
        tempCoefficient: "-0.35%/°C",
        dimensions: "1956x922x30mm",
        weight: "19kg~20kg",
      },
      {
        model: "CE-420W",
        maxPower: "420W (0~+5W)",
        maxPowerVoltage: "31.4V",
        maxPowerCurrent: "13.38A",
        openCircuitVoltage: "34.8V",
        shortCircuitCurrent: "14.18A",
        moduleEfficiency: "≥23%",
        operatingTemp: "-40°C~+85°C",
        maxSystemVoltage: "1000/1500VDC(IEC)",
        maxSeriesFuseRating: "30A",
        powerTolerance: "0~+3%",
        tempCoefficient: "-0.35%/°C",
        dimensions: "1956x922x30mm",
        weight: "19kg~20kg",
      },
    ],
    mechanicalSpecs: {
      cellType: "MONO TOPCon 182x182mm",
      numOfCells: "100 (10x10)",
      frontGlass:
        "3.2mm, Anti-Reflection Coating, High Transmission, Low Iron, Tempered Glass",
      frame: "Anodized Aluminium Alloy",
      junctionBox: "IP68 Rated",
      outputCables: "PV1 x 4.0mm, (+): 500mm, (-): 500mm or Customized Length",
    },
  },
  {
    id: "solar-panel-3",
    category: "Solar Panel",
    series: "CE-500W/550W/600W",
    type: "Mono Half-Cut Solar Panel N-Type",
    description:
      "Positive power tolerance of 0~+3%. TOPCon Technology with Multi Busbar Technology. Excellent Anti-PID performance and high salt mist and ammonia resistance. Enhanced mechanical load certified for extreme conditions.",
    warranty: {
      product: "12-year Product Warranty",
      power: "25-year Linear Power Output Warranty",
      degradation: "0.45% Annual Degradation Over 25 Years",
    },
    certifications: ["ISO9001:2025", "ISO14001:2025", "ISO45001:2025"],
    models: [
      {
        model: "CE-500W",
        maxPower: "500W (0~+5W)",
        maxPowerVoltage: "40.65V",
        maxPowerCurrent: "12.3A",
        openCircuitVoltage: "48.2V",
        shortCircuitCurrent: "13.01A",
        moduleEfficiency: "≥23%",
        operatingTemp: "-40°C~+85°C",
        maxSystemVoltage: "1000/1500VDC(IEC)",
        maxSeriesFuseRating: "30A",
        powerTolerance: "0~+3%",
        tempCoefficient: "-0.35%/°C",
        nominalOperatingCellTemp: "45±2°C",
        dimensions: "1908x1134x30mm",
        weight: "22.5kg",
      },
      {
        model: "CE-550W",
        maxPower: "550W (0~+5W)",
        maxPowerVoltage: "41.95V",
        maxPowerCurrent: "13.12A",
        openCircuitVoltage: "50.34V",
        shortCircuitCurrent: "13.91A",
        moduleEfficiency: "≥23%",
        operatingTemp: "-40°C~+85°C",
        maxSystemVoltage: "1000/1500VDC(IEC)",
        maxSeriesFuseRating: "30A",
        powerTolerance: "0~+3%",
        tempCoefficient: "-0.35%/°C",
        nominalOperatingCellTemp: "45±2°C",
        dimensions: "2279x1134x35mm",
        weight: "27.5kg",
      },
      {
        model: "CE-600W",
        maxPower: "600W (0~+5W)",
        maxPowerVoltage: "41.95V",
        maxPowerCurrent: "14.3A",
        openCircuitVoltage: "50.34V",
        shortCircuitCurrent: "15.16A",
        moduleEfficiency: "≥23%",
        operatingTemp: "-40°C~+85°C",
        maxSystemVoltage: "1000/1500VDC(IEC)",
        maxSeriesFuseRating: "30A",
        powerTolerance: "0~+3%",
        tempCoefficient: "-0.35%/°C",
        nominalOperatingCellTemp: "45±2°C",
        dimensions: "2279x1134x35mm",
        weight: "27.5kg",
      },
    ],
    mechanicalSpecs: {
      cellType: "MONO TOPCon 182x182mm",
      numOfCells: "144 (12x12)",
      frontGlass:
        "3.2mm, Anti-Reflection Coating, High Transmission, Low Iron, Tempered Glass",
      frame: "Anodized Aluminium Alloy",
      junctionBox: "IP68 Rated",
      outputCables: "PV1 x 4.0mm, (+): 500mm, (-): 500mm or Customized Length",
    },
  },
];

export const mpptControllers = [
  {
    id: "mppt-1",
    category: "MPPT Solar Charge Controller",
    series: "MPPT Series",
    description: `This solar charge controller is an advanced solar
charger with maximum power point tracking.
The MPPT battery charging process has been
optimized for long battery life and improved
system Performance. Self-diagnostics and
electronic error protections prevent damage
when installation errors or system faults occur.`,
    features: [
      "Suitable for wide range of battery types (User-Defined/AGM/FLD/LIB)",
      "Multi-stage charging optimizes battery performance",
      "High Efficiency - Maximum efficiency >98%",
      "Intelligent MPPT technology increases 20%-35% efficiency",
      "Maximum charging current up to 120A (Current adjustable)",
    ],
    models: [
      {
        model: "CE-M4048",
        maxBatteryCurrent: "40A",
        batteryType: "User-Defined/AGM/FLD/LIB",
        systemVoltage: "12V/24V/48V DC (Auto detection)",
        pvStartupVoltage: "25V",
        maxSolarInputVoltage: "145V",
        pvArrayMPPTRange: "25/30/60V-120VDC",
        maxSolarPanelInput: {
          "12V": "570W",
          "24V": "1130W",
          "48V": "2270W",
        },
        chargingAlgorithm: "3-Step",
        chargingStages: "Bulk, Absorption, Float",
        operatingTemp: "-25°C~60°C",
        humidity: "0%-90%",
        maxEfficiency: ">98%",
        weight: "1.6kg",
        dimensions: "205x133x76mm",
      },
      {
        model: "CE-M8048",
        maxBatteryCurrent: "80A",
        batteryType: "User-Defined/AGM/FLD/LIB",
        systemVoltage: "12V/24V/48V DC (Auto detection)",
        pvStartupVoltage: "25V",
        maxSolarInputVoltage: "145V",
        pvArrayMPPTRange: "25/30/60V-180VDC (For 12V/24V/48V system)",
        maxSolarPanelInput: {
          "12V": "1130W",
          "24V": "2260W",
          "48V": "4520W",
        },
        chargingAlgorithm: "3-Step",
        chargingStages: "Bulk, Absorption, Float",
        operatingTemp: "-25°C~60°C",
        humidity: "0%-90%",
        maxEfficiency: ">98%",
        weight: "4.2kg",
        dimensions: "280x178x122mm",
      },
      {
        model: "CE-M12048",
        maxBatteryCurrent: "120A",
        batteryType: "User-Defined/AGM/FLD/LIB",
        systemVoltage: "12V/24V/48V DC (Auto detection)",
        pvStartupVoltage: "25V",
        maxSolarInputVoltage: "200V",
        pvArrayMPPTRange: "25/30/60V-180VDC (For 12V/24V/48V system)",
        maxSolarPanelInput: {
          "12V": "1700W",
          "24V": "3400W",
          "48V": "6800W",
        },
        chargingAlgorithm: "3-Step",
        chargingStages: "Bulk, Absorption, Float",
        operatingTemp: "-25°C~60°C",
        humidity: "0%-90%",
        maxEfficiency: ">98%",
        weight: "6.8kg",
        dimensions: "340x215x125mm",
      },
    ],
  },
];

export const inverters = [
  {
    id: "inverter-1",
    category: "Inverter",
    series: "High Frequency Solar Inverter Series",
    type: "CE-H1.8K/CE-H4K/CE-H6K/CE-H12K",
    description:
      "Pure sine wave inverter with built-in MPPT solar charge controller. Configurable input voltage range for home appliances and personal. Configurable battery charging current based on applications via LCD setting. Compatible to main voltage or generator power.",
    features: [
      "Pure sine wave inverter",
      "Built-in MPPT solar charge controller",
      "Configurable input voltage range for home appliances and personal",
      "Configurable battery charging current based on applications via LCD setting",
      "Configurable AC/Solar Charger priority via LCD setting",
      "Compatible to main voltage or generator power",
      "Auto restart while AC is recovering",
      "Overload / Over temperature/ short circuit protection",
      "Inverter running without battery",
      "Lithium battery activation function",
      "Cold start function",
      "Parallel connection quantity up to 12units for 6KVA model (Battery must be connected)",
      "Intelligent fan control greatly reduces fan noise",
    ],
    models: [
      {
        model: "CE-H1.8K",
        ratedOutputPower: "1500W",
        nominalDCInputVoltage: "12V",
        inputVoltageWaveform: "Sinusoidal (Utility or generator)",
        nominalInputVoltage: "230Vac",
        lowLineDisconnect:
          "90Vac±5V (For Home Appliances) / 170Vac±5V (For Computer)",
        lowLineReconnect: "280Vac±5V",
        nominalInputFrequency: "50Hz / 60Hz (Auto detection)",
        efficiencyLinMode: "≥95%",
        transferTime: "10ms typical (UPS); 20ms typical (Appliances)",
        passThroughWithoutBattery: "Yes",
        maxInverterRectifierCurrent: "18.2A/4000W",
        maxGridChargeCurrent: "60A",
        chargeCurrentRegulation:
          "15A-Max. Grid Charge Current (Adjustable up to 14 A)",
        overChargeProtection: "Yes",
        maxPVOpenCircuitVoltage: "500V",
        pvVoltageRange: "85V-450V",
        maxInputPower: "650W",
        maxSolarChargingCurrent: "45A",
        maxInputCurrent: "20A",
        algorithm:
          "Three stage: Boost CC (Constant current stage) -> Boost CV (Constant voltage stage) -> Float PV (Constant voltage stage)",
        batteryTypeSetting: {
          AGM: { boostCC: "28.2V", boostCV: "56.4V", float: "27V/54V" },
          Flooded: { boostCC: "29.2V", boostCV: "58.4V", float: "27V/54V" },
          SelfDefined: "Adjustable, up to 30V/60V",
          Lithium: "Adjustable, up to 30V/60V",
        },
        dcMaxChargingDischargingCurrent: "105A/150A",
        outputVoltageWaveform: "Pure sine wave",
        nominalOutputVoltage: "230Vac±3%",
        nominalOutputFrequency: "50±0.3Hz/60±0.3Hz (Adjustable)",
        parallelCapability: "No",
        peakEfficiency: "≥95%",
        outputCircuitProtection: "Yes",
        highDCInputAlarmFault: "15.5V±0.2V",
        highDCInputRecovery: "14.5V±0.2V ",
        operatingTemperature: "-10°C~55°C",
        rangeStorageTemperature: "-15°C~60°C",
        netWeight: "5.5kg",
        productDimension: "350x290x108mm",
      },
      {
        model: "CE-H4K",
        ratedOutputPower: "4000W",
        nominalDCInputVoltage: "24V",
        inputVoltageWaveform: "Sinusoidal (Utility or generator)",
        nominalInputVoltage: "230Vac",
        lowLineDisconnect:
          "90Vac±5V (For Home Appliances) / 170Vac±5V (For Computer)",
        lowLineReconnect: "280Vac±5V",
        nominalInputFrequency: "50Hz / 60Hz (Auto detection)",
        efficiencyLinMode: ">95% (Rated R load, battery full charged)",
        transferTime: "10ms typical (UPS); 20ms typical (Appliances)",
        passThroughWithoutBattery: "Yes",
        maxInverterRectifierCurrent: "18.2A/4000W",
        maxGridChargeCurrent: "110A",
        chargeCurrentRegulation:
          "15A-Max. Grid Charge Current (Adjustable up to 14 A)",
        overChargeProtection: "Yes",
        maxPVOpenCircuitVoltage: "500V",
        pvVoltageRange: "85V-450V",
        maxInputPower: "4000W",
        maxSolarChargingCurrent: "130A",
        maxInputCurrent: "15A",
        algorithm:
          "Three stage: Boost CC (Constant current stage) -> Boost CV (Constant voltage stage) -> Float PV (Constant voltage stage)",

        batteryTypeSetting: {
          AGM: { boostCC: "28.2V", boostCV: "56.4V", float: "27V/54V" },
          Flooded: { boostCC: "29.2V", boostCV: "58.4V", float: "27V/54V" },
          SelfDefined: "Adjustable, up to 30V/60V",
          Lithium: "Adjustable, up to 30V/60V",
        },
        dcMaxChargingDischargingCurrent: "125A/160A",
        outputVoltageWaveform: "Pure sine wave",
        nominalOutputVoltage: "230Vac±3%",
        nominalOutputFrequency: "50±0.3Hz/60±0.3Hz (Adjustable)",
        parallelCapability: "Yes, up to 12 units",
        peakEfficiency: "≥95%",
        outputCircuitProtection: "Yes",
        highDCInputAlarmFault: "31V±0.2V",
        highDCInputRecovery: "29V±0.2V",
        operatingTemperature: "-10°C~55°C",
        rangeStorageTemperature: "-15°C~60°C",
        netWeight: "9.2kg",
        productDimension: "347x446x120mm",
      },
      {
        model: "CE-H6K",
        ratedOutputPower: "6000W",
        nominalDCInputVoltage: "48V",
        inputVoltageWaveform: "Sinusoidal (Utility or generator)",
        nominalInputVoltage: "230Vac",
        lowLineDisconnect:
          "90Vac±5V (For Home Appliances) / 170Vac±5V (For Computer)",
        lowLineReconnect: "280Vac±5V",
        nominalInputFrequency: "50Hz / 60Hz (Auto detection)",
        efficiencyLinMode: ">95% (Rated R load, battery full charged)",
        transferTime: "10ms typical (UPS); 20ms typical (Appliances)",
        passThroughWithoutBattery: "Yes",
        maxInverterRectifierCurrent: "27.3A/6000W",
        maxGridChargeCurrent: "120A",
        chargeCurrentRegulation:
          "15A-Max. Grid Charge Current (Adjustable up to 14 A)",
        overChargeProtection: "Yes",
        maxPVOpenCircuitVoltage: "500V",
        pvVoltageRange: "85V-450V",
        maxInputPower: "6000W",
        maxSolarChargingCurrent: "120A",
        maxInputCurrent: "27A",
        algorithm:
          "Three stage: Boost CC (Constant current stage) -> Boost CV (Constant voltage stage) -> Float PV (Constant voltage stage)",

        batteryTypeSetting: {
          AGM: { boostCC: "28.2V", boostCV: "56.4V", float: "27V/54V" },
          Flooded: { boostCC: "29.2V", boostCV: "58.4V", float: "27V/54V" },
          SelfDefined: "Adjustable, up to 30V/60V",
          Lithium: "Adjustable, up to 30V/60V",
        },
        dcMaxChargingDischargingCurrent: "106A/125A",
        outputVoltageWaveform: "Pure sine wave",
        nominalOutputVoltage: "230Vac±3%",
        nominalOutputFrequency: "50±0.3Hz/60±0.3Hz (Adjustable)",
        parallelCapability: "Yes, up to 12 units",
        peakEfficiency: "≥95%",
        outputCircuitProtection: "Yes",
        highDCInputAlarmFault: "62V±0.6V",
        highDCInputRecovery: "60V±0.6V",
        operatingTemperature: "-10°C~55°C",
        rangeStorageTemperature: "-15°C~60°C",
        netWeight: "13kg",
        productDimension: "347x446x120mm",
      },
      {
        model: "CE-H12K",
        ratedOutputPower: "12000W",
        nominalDCInputVoltage: "48V",
        inputVoltageWaveform: "Sinusoidal (Utility or generator)",
        nominalInputVoltage: "230Vac",
        lowLineDisconnect:
          "90Vac±5V (For Home Appliances) / 170Vac±5V (For Computer)",
        lowLineReconnect: "280Vac±5V",
        nominalInputFrequency: "50Hz / 60Hz (Auto detection)",
        efficiencyLinMode: ">95% (Rated R load, battery full charged)",
        transferTime: "10ms typical (UPS); 20ms typical (Appliances)",
        passThroughWithoutBattery: "Yes",
        maxInverterRectifierCurrent: "54.5A/12000W",
        maxGridChargeCurrent: "210A",
        chargeCurrentRegulation:
          "15A-Max. Grid Charge Current (Adjustable up to 14 A)",
        overChargeProtection: "Yes",
        maxPVOpenCircuitVoltage: "500V",
        pvVoltageRange: "85V-450V",
        maxInputPower: "12000W",
        maxSolarChargingCurrent: "210A",
        maxInputCurrent: "27Ax2/A",
        algorithm:
          "Three stage: Boost CC (Constant current stage) -> Boost CV (Constant voltage stage) -> Float PV (Constant voltage stage)",

        batteryTypeSetting: {
          AGM: { boostCC: "28.2V", boostCV: "56.4V", float: "27V/54V" },
          Flooded: { boostCC: "29.2V", boostCV: "58.4V", float: "27V/54V" },
          SelfDefined: "Adjustable, up to 30V/60V",
          Lithium: "Adjustable, up to 30V/60V",
        },
        dcMaxChargingDischargingCurrent: "210A/420A",
        outputVoltageWaveform: "Pure sine wave",
        nominalOutputVoltage: "230Vac±3%",
        nominalOutputFrequency: "50±0.3Hz/60±0.3Hz (Adjustable)",
        parallelCapability: "No",
        peakEfficiency: "≥95%",
        outputCircuitProtection: "Yes",
        highDCInputAlarmFault: "62V±0.6V",
        highDCInputRecovery: "60V±0.6V",
        operatingTemperature: "-10°C~55°C",
        rangeStorageTemperature: "-15°C~60°C",
        netWeight: "27kg",
        productDimension: "525x352x125mm",
      },
    ],
  },
  {
    id: "inverter-2",
    category: "Inverter",
    series: "Transformer Based Inverter",
    model: "CE-L10K (10KVA)",
    image: "/transformerbased.webp",
    description:
      "Transformer based inverter with wide range AC input voltage (90-280V). Compatible with 50/60Hz. High charging current with bypass charging function. Supports multiple battery types with comprehensive safety protection.",
    features: [
      "90-280V Wide range of AC input voltage",
      "Compatible with 50/60Hz",
      "Charging and discharge priorities are optional",
      "Comprehensively upgraded safety protection design",
      "High Charging Current",
      "Bypass charging function",
      "Communicate with MPPT",
      "Supports multiple types of batteries",
      "Battery self-defined",
      "Stable performance",
      "Multistage charging, improve battery life",
    ],
    models: [
      {
        model: "CE-L10K (10KVA)",
        ratedOutputPowerVA: "10000VA",
        ratedOutputPowerW: "8000W",
        nominalDCInputVoltage: "48V",
        inputVoltageWaveform: "Sinusoidal (Utility or generator)",
        nominalInputVoltage: "220Vac",
        lowLineDisconnect: "170±7Vac (UPS) / 90±7Vac (APL)",
        lowLineReconnect: "180±7Vac (UPS) / 100±7Vac (APL)",
        acInputRange: "90-280Vac",
        highLineDisconnect: "280±7Vac",
        highLineReconnect: "270±7Vac",
        nominalInputFrequency: "50Hz/60Hz",
        overLoadProtection: "Air switch protection",
        outputShortCircuit: "Air switch protection",
        efficiency: "≥95% (Rated R load, battery fully charged)",
        transferTimeACToDC: "15ms (typical)",
        transferTimeDCToAC: "15ms (typical)",
        maxBypassOverloadCurrent: "AC 63A",
        batteryVoltage: "48V",
        inputVoltageRange: "90-280Vac",
        maxChargeCurrent: "80A",
        chargerShortCircuit: "AC 63A",
        overChargeProtection: "Yes",
        chargingWay: "Three phases: Boost CC → Boost CV → Float",
        batteryTypeSetting: {
          batteryType: { boostCC: "48V", float: "48" },
          AGM: { boostCC: "57.6V", float: "54.4V" },
          Flooded: { boostCC: "58.4V", float: "55.2V" },
          SelfDefined: "Adjustable, up to 61.0V",
        },
        outputVoltageWaveform: "Pure sine wave",
        nominalOutputVoltage: "220Vac ±5%",
        nominalOutputFrequency: "50±0.3Hz / 60±0.3Hz (Adjustable)",
        peakEfficiency: "90%",
        overLoadProtectionOutput: "≤150% load: 10s / 105%-150% load: 2s",
        surgeRating: "2x rated power for 5 seconds",
        coldStartVoltage: "46V",
        operatingTemp: "0°C-40°C",
        storageTemp: "-15°C-60°C",
        weight: "55kg",
        dimensions: "582x446x204mm",
      },
    ],
  },
];

export const lifePO4Batteries = [
  {
    id: "battery-lbd-1",
    category: "LiFePO4 Battery",
    series: "LBD Series",
    description:
      "Safe and long life cycle lithium battery pack with intelligent BMS. Hidden connection design for safety. Comprehensive compatibility with off-grid and hybrid inverters.",
    features: [
      "Safe and long life cycle - recyclable about 6000 times",
      "Intelligent battery protection system",
      "Child and pet friendly with hidden wires and terminals",
      "Comprehensive compatibility with inverters",
    ],
    models: [
      {
        model: "CE-LBD-24200C",
        capacity: "5KWH",
        normalVoltage: "25.6V",
        normalVoltageRange: "24-28.8V",
        chargeCutoffVoltage: "28.8V",
        dischargeCutoffVoltage: "24V",
        maxChargeDischargeCurrent: "150A",
        recommendChargeDischargeCurrent: "≤100A",
        normalOutputPower: "2560W",
        maxOutputPower: "3840W",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        netWeight: "43kg",
        dimensions: "520x360x370mm",
      },
      {
        model: "CE-LBD-48150C",
        capacity: "7.5KWH",
        normalVoltage: "51.2V",
        normalVoltageRange: "48-57.6V",
        chargeCutoffVoltage: "57.6V",
        dischargeCutoffVoltage: "48V",
        maxChargeDischargeCurrent: "150A",
        recommendChargeDischargeCurrent: "≤100A",
        normalOutputPower: "5120W",
        maxOutputPower: "7680W",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        newWeight: "83.5kg",
        dimensions: "680x450x420mm",
      },
    ],
  },
  {
    id: "battery-lbf-1",
    category: "LiFePO4 Battery",
    series: "LBF Series",
    image: "/lbfseries.webp",
    description:
      "High energy lithium battery pack with professional application design. Easy installation with casters for mobility. Safe and long life cycle with up to 20KWH storage capacity.",
    features: [
      "Safe and long life cycle - recyclable about 6000 times",
      "High energy - up to 20KWH storage",
      "Professional application design",
      "Easy installation with casters for mobility",
    ],
    models: [
      {
        model: "CE-LBF-48300C",
        capacity: "15KWH",
        normalVoltage: "51.2V",
        normalVoltageRange: "48-57.6V",
        chargeCutoffVoltage: "57.6V",
        dischargeCutoffVoltage: "48V",
        maxChargeDischargeCurrent: "200A",
        recommendChargeDischargeCurrent: "≤100A",
        normalOutputPower: "5120W",
        maxOutputPower: "10240W",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        netWeight: "129.5kg",
        dimensions: "650x350x725mm",
      },
      {
        model: "CE-LBF-48400C",
        capacity: "20KWH",
        normalVoltage: "51.2V",
        normalVoltageRange: "48-57.6V",
        chargeCutoffVoltage: "57.6V",
        dischargeCutoffVoltage: "48V",
        maxChargeDischargeCurrent: "200A",
        recommendChargeDischargeCurrent: "≤100A",
        normalOutputPower: "5120W",
        maxOutputPower: "10240W",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        netWeight: "135kg",
        dimensions: "700x380x725mm",
      },
    ],
  },
  {
    id: "battery-lbc-1",
    category: "LiFePO4 Battery",
    series: "LBC Series",
    image: "/lbcseries.webp",
    description:
      "Specially designed for home photovoltaic energy storage. Flexible usage with wall mounting and movable wheels. Large-capacity batteries reduce energy storage system costs. BMS monitors safety in real-time.",
    features: [
      "Safe and long life cycle - recyclable about 6000 times",
      "Comprehensive compatibility with inverters",
      "Professional application design for solar systems",
      "Easy installation - floor or wall mounting",
    ],
    models: [
      {
        model: "CE-LBC-48200C",
        capacity: "10KWH",
        normalVoltage: "51.2V",
        normalVoltageRange: "48-57.6V",
        chargeCutoffVoltage: "57.6V",
        dischargeCutoffVoltage: "48V",
        maxChargeDischargeCurrent: "200A",
        recommendChargeDischargeCurrent: "≤100A",
        normalOutputPower: "5120W",
        maxOutputPower: "10240W",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        netWeight: "74.5kg",
        dimensions: "550x380x900mm",
      },
      {
        model: "CE-LBC-48400C",
        capacity: "20KWH",
        normalVoltage: "51.2V",
        normalVoltageRange: "48-57.6V",
        chargeCutoffVoltage: "57.6V",
        dischargeCutoffVoltage: "48V",
        maxChargeDischargeCurrent: "200A",
        recommendChargeDischargeCurrent: "≤100A",
        normalOutputPower: "5120W",
        maxOutputPower: "10240W",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        netWeight: "150kg",
        dimensions: "800x400x200mm",
      },
    ],
  },
  {
    id: "battery-lbt-1",
    category: "LiFePO4 Battery",
    series: "LBT Series",
    image: "/lbtseries.webp",
    description:
      "Safe and long life cycle LiFePO4 battery pack with intelligent BMS and modular design, suitable for industrial and civil use.",
    features: [
      "Safe and long life cycle - recyclable about 6000 times",
      "Intelligent BMS for stability and safety",
      "Modular design for reliability and standardization",
      "Comprehensive compatibility with off-grid and hybrid inverters",
    ],
    models: [
      {
        model: "CE-LBT-48100C",
        capacity: "5KWH",
        normalVoltage: "51.2V",
        normalVoltageRange: "48-57.6V",
        chargeCutoffVoltage: "57.6V",
        dischargeCutoffVoltage: "48V",
        maxChargeDischargeCurrent: "100A",
        recommendChargeDischargeCurrent: "≤60A",
        normalOutputPower: "3072W",
        maxOutputPower: "5120W",
        communicationPort: "RS485, CAN",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        netWeight: "45kg",
        dimensions: "470x440x185mm",
      },
      {
        model: "CE-LBT-24100C",
        capacity: "2.5KWH",
        normalVoltage: "25.6V",
        normalVoltageRange: "24-28.8V",
        chargeCutoffVoltage: "28.8V",
        dischargeCutoffVoltage: "24V",
        maxChargeDischargeCurrent: "100A",
        recommendChargeDischargeCurrent: "≤60A",
        normalOutputPower: "1536W",
        maxOutputPower: "2560W",
        communicationPort: "/",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        netWeight: "31.2kg",
        dimensions: "480x320x195mm",
      },
    ],
  },
  {
    id: "battery-lbw-1",
    category: "LiFePO4 Battery",
    series: "LBW Series",
    image: "/lbwseries.jpeg",
    description:
      "Specially designed for home energy storage with flexible wall mounting. BMS monitors battery safety in real-time. Comprehensive compatibility with inverters.",
    features: [
      "Safe and long life cycle - recyclable about 6000 times",
      "Intelligent BMS for stability and safety",
      "Comprehensive compatibility with inverters",
      "Easy installation - floor or wall mounting",
    ],
    models: [
      {
        model: "CE-LBW-24100C",
        capacity: "2.5KWH",
        normalVoltage: "25.6V",
        normalVoltageRange: "24-28.8V",
        chargeCutoffVoltage: "28.8V",
        dischargeCutoffVoltage: "24V",
        maxChargeDischargeCurrent: "100A",
        recommendChargeDischargeCurrent: "≤60A",
        normalOutputPower: "1536W",
        maxOutputPower: "2560W",
        communicationPort: "RS485, CAN",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        netWeight: "35.5kg",
        dimensions: "550x360x230mm",
      },
      {
        model: "CE-LBW-48100C",
        capacity: "5KWH",
        normalVoltage: "51.2V",
        normalVoltageRange: "48-57.6V",
        chargeCutoffVoltage: "57.6V",
        dischargeCutoffVoltage: "48V",
        maxChargeDischargeCurrent: "100A",
        recommendChargeDischargeCurrent: "≤60A",
        normalOutputPower: "3072W",
        maxOutputPower: "5120W",
        communicationPort: "RS485, CAN",
        parallelConnection: "1-6",
        ingressProtection: "IP21",
        cycleTimes: "≥6000@80% DOD, 25°C, 0.5C",
        workingTemp: "-10°C~60°C",
        netWeight: "63kg",
        dimensions: "603x490x230mm",
      },
    ],
  },
  {
    id: "battery-gcl-1",
    category: "LiFePO4 Battery",
    series: "GCL Series",
    image: "/gclseries.webp",
    description:
      "Modular design lithium battery with intelligent BMS. Industrial quality design suitable for industrial and civil use. Comprehensive compatibility with inverters.",
    features: [
      "Safe and long life cycle - recyclable about 3200 times",
      "Intelligent BMS for stability and safety",
      "Modular design for reliability",
      "Comprehensive compatibility with inverters",
    ],
    models: [
      {
        model: "CE-GCL-12100",
        capacity: "1.28KWH",
        normalVoltage: "12.8V",
        normalVoltageRange: "12-14.4V",
        chargeCutoffVoltage: "14.4V",
        dischargeCutoffVoltage: "12V",
        maxChargeDischargeCurrent: "100A",
        recommendChargeDischargeCurrent: "≤50A",
        normalOutputPower: "640W",
        maxOutputPower: "1280W",
        serialUse: "Up to 2",
        parallelConnection: "Up to 4",
        ingressProtection: "IP21",
        cycleTimes: "≥3200@25°C",
        workingTemp: "-10°C~60°C",
        netWeight: "17.2kg",
        dimensions: "320x205x247mm",
      },
      {
        model: "CE-GCL-12150",
        capacity: "1.92KWH",
        normalVoltage: "12.8V",
        normalVoltageRange: "12-14.4V",
        chargeCutoffVoltage: "14.4V",
        dischargeCutoffVoltage: "12V",
        maxChargeDischargeCurrent: "100A",
        recommendChargeDischargeCurrent: "≤50A",
        normalOutputPower: "640W",
        maxOutputPower: "1280W",
        serialUse: "Up to 2",
        parallelConnection: "Up to 4",
        ingressProtection: "IP21",
        cycleTimes: "≥3200@25°C",
        workingTemp: "-10°C~60°C",
        netWeight: "17.4kg",
        dimensions: "380x240x260mm",
      },
      {
        model: "CE-GCL-12200",
        capacity: "2.56KWH",
        normalVoltage: "12.8V",
        normalVoltageRange: "12-14.4V",
        chargeCutoffVoltage: "14.4V",
        dischargeCutoffVoltage: "12V",
        maxChargeDischargeCurrent: "150A",
        recommendChargeDischargeCurrent: "≤100A",
        normalOutputPower: "1280W",
        maxOutputPower: "1920W",
        serialUse: "Up to 2",
        parallelConnection: "Up to 4",
        ingressProtection: "IP21",
        cycleTimes: "≥3200@25°C",
        workingTemp: "-10°C~60°C",
        netWeight: "17.6kg",
        dimensions: "380x240x277mm",
      },
      {
        model: "CE-GCL-12250",
        capacity: "3.2KWH",
        normalVoltage: "12.8V",
        normalVoltageRange: "12-14.4V",
        chargeCutoffVoltage: "14.4V",
        dischargeCutoffVoltage: "12V",
        maxChargeDischargeCurrent: "150A",
        recommendChargeDischargeCurrent: "≤100A",
        normalOutputPower: "1280W",
        maxOutputPower: "1920W",
        serialUse: "Up to 2",
        parallelConnection: "Up to 4",
        ingressProtection: "IP21",
        cycleTimes: "≥3200@25°C",
        workingTemp: "-10°C~60°C",
        netWeight: "23kg",
        dimensions: "380x240x277mm",
      },
      {
        model: "CE-GCL-12300",
        capacity: "3.84KWH",
        normalVoltage: "12.8V",
        normalVoltageRange: "12-14.4V",
        chargeCutoffVoltage: "14.4V",
        dischargeCutoffVoltage: "12V",
        maxChargeDischargeCurrent: "150A",
        recommendChargeDischargeCurrent: "≤100A",
        normalOutputPower: "1280W",
        maxOutputPower: "1920W",
        serialUse: "Up to 2",
        parallelConnection: "Up to 4",
        ingressProtection: "IP21",
        cycleTimes: "≥3200@25°C",
        workingTemp: "-10°C~60°C",
        netWeight: "29kg",
        dimensions: "380x240x277mm",
      },
    ],
  },
];

export const gelBatteries = [
  {
    id: "battery-gel-1",
    category: "GEL Battery",
    series: "GEL Series",
    description:
      "Silica gel electrolyte lead acid batteries with deep discharge capability. Sulfuric acid exists in colloid form - solid, not easy to leak. Can be placed vertically or horizontally with comprehensive floating charging design.",
    features: [
      "Safe and long life cycle - deep discharge capability",
      "Solve electrolyte stratification and sulfuric acid leakage",
      "Comprehensive design of floating charging",
      "No acid mist gas precipitation, no electrolyte overflow",
      "More stable performance under extreme temperatures (-40°C to 65°C)",
      "Environmentally friendly and economical",
    ],
    models: [
      {
        model: "G-12V 100AH",
        cellsPerUnit: "6",
        voltagePerUnit: "12",
        capacity: "100Ah@10hr-rate to 1.80V per cell @25°C",
        maxDischargeCurrent: "1000A (5 sec)",
        internalResistance: "Approx. 5.0mΩ",
        recommendedMaxChargingCurrent: "30A",
        operatingTempRange: {
          discharge: "-20°C~60°C",
          charge: "0°C~50°C",
          storage: "-20°C~60°C",
        },
        normalOperatingTemp: "25°C ± 5°C",
        floatChargingVoltage: "13.6 to 13.8V DC/unit Average at 25°C",
        equalizationVoltage: "14.4 to 14.6V DC/unit Average at 25°C",
        selfDischarge:
          "GEL batteries can be stored for more than 6 months at 25°C. Self-discharge ratio less than 3% per month at 25°C. Please charge batteries before using.",
        weight: "27.8kg",
        dimensions: "330x171x218mm",
      },
      {
        model: "G-12V 200AH",
        cellsPerUnit: "6",
        voltagePerUnit: "12",
        capacity: "200Ah@10hr-rate to 1.80V per cell @25°C",
        maxDischargeCurrent: "2000A (5 sec)",
        internalResistance: "Approx. 4.0mΩ",
        recommendedMaxChargingCurrent: "60A",
        operatingTempRange: {
          discharge: "-20°C~60°C",
          charge: "0°C~50°C",
          storage: "-20°C~60°C",
        },
        normalOperatingTemp: "25°C ± 5°C",
        floatChargingVoltage: "13.6 to 13.8V DC/unit Average at 25°C",
        equalizationVoltage: "14.4 to 14.6V DC/unit Average at 25°C",
        selfDischarge:
          "GEL batteries can be stored for more than 6 months at 25°C. Self-discharge ratio less than 3% per month at 25°C. Please charge batteries before using.",
        weight: "56.0kg",
        dimensions: "522x220x240mm",
      },
    ],
  },
];

export const streetLights = [
  {
    id: "streetlight-c-series",
    category: "Street Light",
    series: "C1/C2 Series",
    description:
      "Integrated solar street light with high capacity LiFePO4 battery and Philips LED chip. High efficient solar cell (>23%) with intelligent controller. Convenient installation with modular design.",
    features: [
      "Integrated design with high capacity LiFePO4 lithium battery",
      "Philips LED chip with 180LM/W efficiency, whole lamp 160LM/W",
      "High efficiency intelligent controller (15%-30% charge efficiency increase)",
      "High efficiency solar cell (>23%)",
      "Convenient installation - no cable needed, modular design",
    ],
    models: [
      {
        model: "CE-C2-C60W",
        solarPanel: "65W ",
        battery: "340WH",
        luminousFlux: "14400lm",
        recommendInstallHeight: "4-5m",
        solarPanelChargeTime: "8 hours by bright sunlight",
        rainyDaysSupport: ">5 days with full charging",
        workingTimePerDay: "≥12 hours",
        colorTemperature: "6500K",
        lightPoleDiameter: "84mm",
        storageTemp: "0-55°C",
        operatingHumidity: "≤90%RH",
        waterproofLevel: "IP65",
        dimensions: "1159x394x65mm",
      },
      {
        model: "CE-C2-C100W",
        solarPanel: "105W ",
        battery: "560WH",
        luminousFlux: "21600lm",
        recommendInstallHeight: "4-7m",
        solarPanelChargeTime: "8 hours by bright sunlight",
        rainyDaysSupport: ">5 days with full charging",
        workingTimePerDay: "≥12 hours",
        colorTemperature: "6500K",
        lightPoleDiameter: "84mm",
        storageTemp: "0-55°C",
        operatingHumidity: "≤90%RH",
        waterproofLevel: "IP65",
        dimensions: "1489x394x65mm",
      },
      {
        model: "CE-C1-100W",
        solarPanel: "145W ",
        battery: "920WH",
        luminousFlux: "30200lm",
        recommendInstallHeight: "6-9m",
        solarPanelChargeTime: "8 hours by bright sunlight",
        rainyDaysSupport: "3-5 days with full charging",
        workingTimePerDay: "≥12 hours",
        colorTemperature: "6500K",
        lightPoleDiameter: "114mm",
        storageTemp: "0-55°C",
        operatingHumidity: "≤90%RH",
        waterproofLevel: "IP65",
        dimensions: "1600x489x69mm",
      },
    ],
  },
  {
    id: "streetlight-tk-series",
    category: "Street Light",
    series: "TK Series",
    image: "/tkseries.webp",
    description:
      "High brightness solar street light supporting multiple mounting options (ground, wall, pole). High capacity LiFePO4 battery with Philips LED chip and efficient intelligent controller.",
    features: [
      "High Brightness - supports ground, wall, and pole fixation",
      "High capacity LiFePO4 lithium battery",
      "Philips LED chip with 180LM/W efficiency, whole lamp 160LM/W",
      "High efficiency intelligent controller (15%-30% charge efficiency increase)",
      "High efficiency solar cell (>23%)",
    ],
    models: [
      {
        model: "CE-TK-60W",
        solarPanel: "60W",
        battery: "256WH",
        luminousFlux: "11376lm",
        recommendInstallHeight: "3-6m",
        solarPanelChargeTime: "8 hours by bright sunlight",
        rainyDaysSupport: ">5 days with full charging",
        workingTimePerDay: "≥12 hours",
        colorTemperature: "3000-7000K",
        lightPoleDiameter: "76mm",
        storageTemp: "0-55°C",
        operatingHumidity: "≤90%RH",
        waterproofLevel: "IP65",
        weight: "6.75kg",
        dimensions: "310x310x110mm",
      },
      {
        model: "CE-TK-80W",
        solarPanel: "80W",
        battery: "320WH",
        luminousFlux: "11376lm",
        recommendInstallHeight: "3-6m",
        solarPanelChargeTime: "8 hours by bright sunlight",
        rainyDaysSupport: ">5 days with full charging",
        workingTimePerDay: "≥12 hours",
        colorTemperature: "3000-7000K",
        lightPoleDiameter: "76mm",
        storageTemp: "0-55°C",
        operatingHumidity: "≤90%RH",
        waterproofLevel: "IP65",
        weight: "7.8kg",
        dimensions: "430x320x95mm",
      },
    ],
  },
];

export const portableSolarSystems = [
  {
    id: "portable-1",
    category: "Portable Solar Power System",
    series: "CS-PLB1200 Series",
    description:
      "Portable solar system with built-in MPPT controller, integrating lithium batteries and inverters. Ideal for charging devices and powering home appliances.",
    features: [
      "Portable design",
      "Built in MPPT controller",
      "Support for mains and solar panel charging",
      "Integrating lithium batteries, inverters",
      "LCD screen, with LED lights",
    ],
    models: [
      {
        model: "CS-PLB1200",
        battery: "25.6V 1.5KWH",
        inverterPowerDefault: "1200W 230VAC 50Hz",
        led: "3W",
        dc5521: "12V 10A",
        usb1: "18W*2 5V/9V/12V",
        usb2: "12W*2 5V",
        typeC1: "PD100W 5V/9V/12V/15V/20V",
        typeC2: "PD45W 5V/9V/12V/15V/20V",
        maxPVInputMPPT: "500W 60V 12A",
        acInputVoltageRange: "185-275V",
        utilityPVChargePower: "1050W",
        expandCapacity: "CWORTH Energy 24V battery",
        workingTemperature: "-10°C~45°C",
        netWeight: "18kg",
        productDimension: "385x230x280mm",
      },
    ],
  },
];

export const distributionBox = [
  {
    id: "ebox-1",
    category: "Distribution Box",
    series: "E-BOX Series",
    description:
      "Provides current and voltage visualization. Protects MPPT controller and inverter from damage. Prevents inverter damage due to excessive input voltage fluctuation.",
    features: [
      "Current and voltage visualization",
      "Prevent damage to MPPT controller and inverter caused by lightning strikes",
      "Prevent inverter damage due to excessive input voltage fluctuation of the power grid",
      "Prevent inverter output short circuit or excessive load from causing damage to the inverter and controlling the customer's usage overload",
    ],
    models: [
      {
        model: "E-BOX",
        acRatingVoltageRated: "AC 220V",
        acOperationVoltageRange: "AC 80V~330V",
        acRatedCurrent: "63A",
        acElectricCurrentL1SettingRange: "1~63A",
        displayResetStartDelay: "1s~600s",
        voltageMeasurementAccuracy: "1%",
        acGridFrequency: "50/60Hz",
        levelsOfProtection: "IP30",
        workingTemperature: "-15°C~60°C",
        dcInputVoltageAndCurrent: "<500V/63A",
        netWeight: "2.82kg",
        productDimension: "360x210x90mm",
      },
    ],
  },
];

export const offGridSolarSystem = [
  {
    id: "solar-system-1",
    category: "Solar Energy System",
    series: "Off-Grid Solar Energy System",
    description:
      "Renewable environmental protection system suitable for various applications like residential, industrial, and agricultural use. Supplies power for household appliances and office equipment.",
    features: [
      "High quality",
      "Professional solutions",
      "Prevent electricity outages",
      "Reduce your energy bills",
      "Easy installation",
      "Keeping the environment clean and green",
    ],
    models: [
      {
        model: "1.5KW",
        solarPanel: "2 Pieces * 200W 27.1V",
        inverter: "1.5KW DC 12V / AC 230V, 50Hz/60Hz / MPPT 45A * 1 unit",
        lithiumBattery: "CE-GCL-12100 / 1.28KWH * 1 unit",
        eBox: "1 pc",
        pvFrame: "1 * set",
        pvCable: {
          red: "4mm² * 20m",
          black: "4mm² * 20m",
        },
      },
      {
        model: "4KW",
        solarPanel: "4 Pieces * 400W 34.8V",
        inverter: "4KW DC 24V / AC 230V, 50Hz/60Hz / MPPT 120A * 1 unit",
        lithiumBattery: "CE-LBD-24200C / 5KWH * 1 unit",
        eBox: "1 pc",
        pvFrame: "1 * set",
        pvCable: {
          red: "4mm² * 20m",
          black: "4mm² * 20m",
        },
      },
      {
        model: "6KW",
        solarPanel: "6 Pieces * 550W 46.2V",
        inverter: "6KW DC 48V / AC 230V, 50Hz/60Hz / MPPT 120A * 1 unit",
        lithiumBattery: "CE-LBC-48200C / 10KWH * 1 unit",
        eBox: "1 pc",
        pvFrame: "1 * set",
        pvCable: {
          red: "4mm² * 20m",
          black: "4mm² * 20m",
        },
      },
      {
        model: "8KW",
        solarPanel: "8 Pieces * 550W 46.2V",
        inverter: "6KW DC 48V / AC 230V, 50Hz/60Hz / MPPT 120A * 1 unit",
        lithiumBattery: "CE-LBF-48300C / 15KWH * 1 unit",
        eBox: "1 pc",
        pvFrame: "1 * set",
        pvCable: {
          red: "4mm² * 20m",
          black: "4mm² * 20m",
        },
      },
      {
        model: "12KW",
        solarPanel: "12 Pieces * 550W 46.2V",
        inverter: "12KW DC 48V / AC 230V, 50Hz/60Hz / MPPT 210A * 1 unit",
        lithiumBattery: "CE-LBC-48400C / 20KWH * 1 unit",
        eBox: "1 pc",
        pvFrame: "1 * set",
        pvCable: {
          red: "4mm² * 40m",
          black: "4mm² * 40m",
        },
      },
    ],
  },
];

export const solarProducts = [
  {
    title: "Solar Panel",
    description:
      "High-efficiency photovoltaic panels that convert sunlight into DC power, suitable for residential and commercial systems.",
    specs: [
      "Wattage: 400–500 W per panel",
      "Voltage: 31–41 V",
      "Current: 12 A",
      "Operating Temp: –40°C to +85°C",
      "Power Tolerance: ±3%",
    ],
    image: "/solarpanel.png",
    dataSource: solarPanels,
  },
  {
    title: "MPPT Controller",
    description:
      "Smart controllers that maximize energy harvest from solar panels while protecting your batteries.",
    specs: [
      "Compatible Voltages: 12 V, 24 V, 48 V",
      "Max Battery Current: up to 120 A",
      "Max Solar Input Voltage: ~200 V",
      "Efficiency: >98%",
      "Charging Algorithm: Bulk, Absorption, Float",
      "Operating Temp: –25°C to +60°C",
    ],
    image: "/mppt.png",
    dataSource: mpptControllers,
  },
  {
    title: "Inverter",
    description:
      "Inverters that convert DC from batteries or solar panels into AC power with built-in MPPT.",
    specs: [
      "Power Rating: up to 12 kVA",
      "DC Input Voltage: 12 V / 24 V / 48 V",
      "MPPT Voltage Range: 85–450 V",
      "Peak Efficiency: 93–95%",
      "Waveform: Pure sine wave",
      "Protections: Overload, short circuit, over-temp",
    ],
    image: "/inverter.webp",
    dataSource: inverters,
  },
  {
    title: "LiFePO4 Battery",
    description:
      "Long-life lithium iron phosphate batteries for deep discharge and frequent cycling.",
    specs: [
      "Voltage: 48 V",
      "Capacity: 15 kWh",
      "Cycle Life: ≥6000 cycles @ 80% DoD",
      "BMS: Built-in protection system",
      "Operating Temp: –10°C to +60°C",
      "Weight: ~130 kg",
    ],
    image: "/po4battery.webp",
    dataSource: lifePO4Batteries,
  },
  {
    title: "Gel Battery Series",
    description:
      "Maintenance-free deep-cycle batteries, reliable for solar backup applications.",
    specs: [
      "Voltage: 12–48 V",
      "Deep-cycle design",
      "Maintenance-free",
      "Durable under moderate cycling",
      "Suitable for residential or commercial backup",
    ],
    image: "/gelbattery.webp",
    dataSource: gelBatteries,
  },
  {
    title: "Street Light",
    description:
      "Integrated solar street lights combining panel, battery, and LEDs for outdoor lighting.",
    specs: [
      "LED Power: 60–100 W",
      "Battery: 340–920 Wh",
      "Waterproof Rating: IP65",
      "Rainy Day Support: 3–5 days autonomy",
      "Recommended Mounting Height: 6–9 m",
    ],
    image: "/streetlight.webp",
    dataSource: streetLights,
  },
  {
    title: "Portable Solar Power System",
    description:
      "Portable solar power system with integrated panel, battery, and inverter for self-sufficiency.",
    specs: [
      "Integrated panel + battery",
      "Output: DC/AC via built-in inverter",
      "Battery Type: LiFePO₄",
      "Protection: Overcharge, deep discharge, thermal",
      "Easy setup: plug-and-play",
    ],
    image: "/portablesolar.webp",
    dataSource: portableSolarSystems,
  },
  {
    title: "Distribution Box (E-Box)",
    description:
      "Protects MPPT controller and inverter from damage. Prevents inverter damage due to excessive input voltage fluctuation.",
    specs: [
      "PV Capacity: 6–12 kW",
      "Inverter: 6–12 kVA hybrid",
      "Battery Storage: 15 kWh+",
      "Controller: MPPT included",
      "Includes all panels, frame, cables, and installation plan",
    ],
    image: "/ebox.webp",
    dataSource: distributionBox,
  },
  {
    title: "Off-Grid Solar System",
    description:
      "Complete solar system for off-grid applications. Includes panel, battery, inverter, and distribution box.",
    specs: [
      "PV Capacity: 6–12 kW",
      "Inverter: 6–12 kVA hybrid",
      "Battery Storage: 15 kWh+",
      "Controller: MPPT included",
      "Includes all panels, frame, cables, and installation plan",
    ],
    image: "/solarsystem.webp",
    dataSource: offGridSolarSystem,
  },
];
